### ISSUE TITLE
Branching rules

### ISSUE THREAD

**Issue by matheusdiogenesandrade** [scipopt/SCIPpp#8]
Is there any [branching rule](https://www.scipopt.org/doc/html/BRANCH.php) support? Or can it be used through the SCIP C API?

Thanks and BR.

**Comment by hedtke** [comment]
I added a new test case that checks whether one can use ObjSCIP together with SCIP++. That works well as one can access the underlying SCIP pointer via `Model::scip()`. See https://github.com/scipopt/SCIPpp/blob/main/test/test_objscip.cpp

I could also add new methods like `Model::addEventhdlr` which would allow code such as

```cpp
Model model("Simple");
model.addEventhdlr<MyEventHandler>();
```

instead of

```cpp
Model model("Simple");
SCIPincludeObjEventhdlr(model.scip(), new MyEventHandler(model.scip()), true);
```

Is that what you are looking for?

**Comment by matheusdiogenesandrade** [comment]
> Is that what you are looking for?

Yes, exactly this. Thanks.
